### ISSUE TITLE
Remove unwanted/un-used pages on current site

### ISSUE THREAD

**Issue by JCKing97** [JCKing97/EdenbridgeCCPlayCricket#7]
# Task

We want the website to be clean and important information to be easily accessible.

To achieve this we will remove any unwanted/un-used pages on the current site.

# To Do

- [ ] Analyse what pages have been visited and when (coming up with a list of unused pages to remove)
- [ ] Find any pages with outdated information (either we update the information or remove it)
- [ ] Ask the committee if there are any pages they no longer want

**Comment by JCKing97** [comment]
# Junior Honours Board

This page is empty and unused, let's either develop it or remove it.

**Comment by JCKing97** [comment]
# Members Board

Page is empty and unused, remove or develop?

**Comment by JCKing97** [comment]
# Club honours board

Page is empty and unused, remove or develop?

**Comment by JCKing97** [comment]
Pages have been unlinked/hidden that are currently not filled in:

- Club honours board
- Photo Gallery
- Members board
- Junior Honours Board
- Match reports
